name: "HCL AppScan SAST"
on:
  workflow_dispatch
  #pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.1
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 5ef64671-56d8-4e52-a2a5-6c4f9902a486
          #wait_for_analysis: true
          #fail_for_noncompliance: true

